apiVersion: v1
kind: Service
metadata:
  name: uat-els-easysme-be-service
  labels: 
    app: uat-els-easysme-be
spec:
  type: NodePort
  selector:
    app: uat-els-easysme-be
  ports: 
    - port: 9000
      targetPort: 9000
